name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version string (eg. 6.1)
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install git+git://github.com/glutanimate/anki-addon-builder.git@4039b5bb743773a18cb2911e6dd38fa1e3f65982
          python -m pip install pyqt5
          
      - name: Commit changes to git
        uses: EndBug/add-and-commit@v7.1.1
        with:
          message: Bump Version to v${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.version }}
        
      - name: Create ankiaddon file
        run: aab build
      
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=module_name::$(ls src)"
     
      - name: Create github release and upload ankiaddon file
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ github.token }}
          file: build/${{ steps.vars.outputs.module_name }}-${{ steps.vars.outputs.sha_short }}-anki21.ankiaddon
          tag: ${{ github.event.inputs.version }}
          release_name: ${{ steps.vars.outputs.module_name }} v${{ github.event.inputs.version }}